// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO conversation_participant (conversation_id, user_id)
VALUES ($1, $2)
RETURNING conversation_id, user_id, joined_at
`

type AddParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(&i.ConversationID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversation (type)
VALUES ($1)
RETURNING id, type, created_at
`

func (q *Queries) CreateConversation(ctx context.Context, type_ string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, type_)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT id, conversation_id, sender_id, content, created_at FROM message
WHERE conversation_id = $1
  AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type GetConversationMessagesParams struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.ConversationID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT user_id FROM conversation_participant
WHERE conversation_id = $1
`

func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
    SELECT 1
    FROM conversation_participant
    WHERE conversation_id = $1
        AND user_id = $2
) AS is_participant
`

type IsParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}
