// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO conversation_participant (conversation_id, user_id)
VALUES ($1, $2)
RETURNING conversation_id, user_id, joined_at, last_read_at
`

type AddParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.JoinedAt,
		&i.LastReadAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversation (type)
VALUES ($1)
RETURNING id, type, created_at
`

func (q *Queries) CreateConversation(ctx context.Context, type_ string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, type_)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, created_at, content_tsv
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.ContentTsv,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT id, conversation_id, sender_id, content, created_at, content_tsv FROM message
WHERE conversation_id = $1
  AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type GetConversationMessagesParams struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, arg.ConversationID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.ContentTsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT user_id FROM conversation_participant
WHERE conversation_id = $1
`

func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM message m
JOIN conversation_participant cp ON cp.conversation_id = m.conversation_id
WHERE m.conversation_id = $1
  AND cp.user_id = $2
  AND m.created_at > cp.last_read_at
`

type GetUnreadCountParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, arg.ConversationID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
    SELECT 1
    FROM conversation_participant
    WHERE conversation_id = $1
        AND user_id = $2
) AS is_participant
`

type IsParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id, c.type, c.created_at FROM conversation c
JOIN conversation_participant cp ON cp.conversation_id = c.id
WHERE cp.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListUserConversations(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE conversation_participant
SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type MarkAsReadParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ConversationID, arg.UserID)
	return err
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.content, m.created_at, m.content_tsv FROM message m
JOIN conversation_participant cp ON cp.conversation_id = m.conversation_id
WHERE cp.user_id = $1
  AND m.content_tsv @@ plainto_tsquery('english', $2)
ORDER BY m.created_at DESC
LIMIT $3
`

type SearchMessagesParams struct {
	UserID         uuid.UUID `json:"user_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.UserID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.ContentTsv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
