ALTER TABLE users ALTER COLUMN created_at SET DATA TYPE TIMESTAMP;
ALTER TABLE users RENAME COLUMN created_at TO create_at;
ALTER TABLE users RENAME COLUMN password_hash TO hashed_password;

ALTER TABLE users
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id SET DATA TYPE INTEGER USING 0;